### ISSUE TITLE
guardian and iboss detects the page "/games" 

### ISSUE THREAD

**Issue by Kelderman** [Skoolgq/Polaris#17]
change link.com/games to link.com/gs.
such for the other sites

(like pretty much any other site)
![Screenshot 2024-01-09 222149](https://github.com/Skoolgq/Polaris/assets/150567391/4147d60e-222a-4ca4-a6d2-c09a5c86d7e6)

**Comment by Russell2259** [comment]
We will not be changing the games path. However, you can self host polaris and rename the games.html to something that is not blocked at your school.

**Comment by Kelderman** [comment]
all thats what you need to do? or in the code u have to still change it to read that .html

**Comment by Russell2259** [comment]
You would change it from "games.html" to "whateveryouwant.html"

**Comment by EnchantedDonutStudioz** [comment]
> change link.com/games to link.com/gs. such for the other sites
> 
> (like pretty much any other site) ![Screenshot 2024-01-09 222149](https://private-user-images.githubusercontent.com/150567391/295434006-4147d60e-222a-4ca4-a6d2-c09a5c86d7e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTc1MzAsIm5iZiI6MTcwNDg1NzIzMCwicGF0aCI6Ii8xNTA1NjczOTEvMjk1NDM0MDA2LTQxNDdkNjBlLTIyMmEtNGNhNC1hNmQyLWMwOWE1Yzg2ZDdlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwMzI3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDliNzYyMGY3NzAzZTdhM2E4ZjliNjUzN2RlMWY2ZWU5NTQzMjc0NzllYjQ5OWVjYmRjNjdkZjA0ZmQ3NjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U2_A1AVGS5gUs2Yc9x_SkTJt5FXSjwm_ld8hu0Dpo90)

How did you selfhost polaris?

**Comment by Russell2259** [comment]
We have a vps that runs official polaris links. If you want to host it yourself, the local/server deployment instructions are located here: https://github.com/Skoolgq/Polaris#readme

**Comment by fowntain** [comment]
> We will not be changing the games path. However, you can self host polaris and rename the games.html to something that is not blocked at your school.

I think we might want to consider this because links will get blocked costing us lots of money. Maybe something like /choose.html
