### ISSUE TITLE
Most Now.gg games are broken

### ISSUE THREAD

**Issue by UnderC0verGoose** [Skoolgq/Polaris#23]
Most of the now.gg games are broken and are giving me UI bugs when loaded or clicked.
![Screenshot 2024-01-21 7 52 31 PM](https://github.com/Skoolgq/Polaris/assets/65687266/cb1850b7-3672-43b6-8762-4fc5ef4b0ef3)

**Comment by Russell2259** [comment]
Now.gg has gotten a UI update that has broken it for some users. For some users it has also fixed itself. Clearing your cache (https://support.google.com/accounts/answer/32050) should flush out any old data that may be causing the bug.

**Comment by UnderC0verGoose** [comment]
> Now.gg has gotten a UI update that has broken it for some users. For some users it has also fixed itself. Clearing your cache (https://support.google.com/accounts/answer/32050) should flush out any old data that may be causing the bug.

I've cleared the cache and tried again, and it still has stayed the same.

**Comment by fowntain** [comment]
> > Now.gg has gotten a UI update that has broken it for some users. For some users it has also fixed itself. Clearing your cache (https://support.google.com/accounts/answer/32050) should flush out any old data that may be causing the bug.
> 
> I've cleared the cache and tried again, and it still has stayed the same.

Is this still an issue? @UnderC0verGoose

**Comment by UnderC0verGoose** [comment]
> > > Now.gg has gotten a UI update that has broken it for some users. For some users it has also fixed itself. Clearing your cache (https://support.google.com/accounts/answer/32050) should flush out any old data that may be causing the bug.
> > 
> > 
> > I've cleared the cache and tried again, and it still has stayed the same.
> 
> Is this still an issue? @UnderC0verGoose

No, it has fixed.

**Comment by Russell2259** [comment]
If this error occurs again please reopen this issue.

**Comment by UnderC0verGoose** [comment]
This issue has happened again, but instead of all the games being like this, it only happens for certain games, and the site is broken when used in the proxy.
