### ISSUE TITLE
Lots of stuff isn't loading...

### ISSUE THREAD

**Issue by bcrhbrhcdb** [Skoolgq/Polaris#24]
![Screenshot 2024-01-24 10 14 41](https://github.com/Skoolgq/Polaris/assets/123518949/6f761925-1aee-40f9-a844-d9d30484295e)

**Comment by Russell2259** [comment]
The navbar is inserted server-side. If you are self hosting polaris or running it on services like vercel, polaris breaks and is unable to insert the navbar.

**Comment by Russell2259** [comment]
This issue is already open #22

**Comment by bcrhbrhcdb** [comment]
Is there any way to fix it?

**Comment by Russell2259** [comment]
Are you using vercel to host it?

**Comment by bcrhbrhcdb** [comment]
Yes

**Comment by Russell2259** [comment]
Then not much

**Comment by bcrhbrhcdb** [comment]
Is there a different way i can host it?

**Comment by bcrhbrhcdb** [comment]
without it breaking its self

**Comment by Russell2259** [comment]
You could self host it or try another platform like render.
