### ISSUE TITLE
Now.gg Games Broken (Issue can't be re-opened unless said person is a collaborator).

### ISSUE THREAD

**Issue by UnderC0verGoose** [Skoolgq/Polaris#26]
This issue has happened again, but instead of all the games being like this, it only happens for certain games, and the site is broken when used in the proxy. The issue doesn't allow me to re-open it because it requires the person or author to be a collaborator.

_Originally posted by @UnderC0verGoose in https://github.com/Skoolgq/Polaris/issues/23#issuecomment-1918230397_

**Comment by Russell2259** [comment]
@UnderC0verGoose We cannot fix this bug as it caused by now.gg. Please do not open any more issues regarding this.
