### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by UnderC0verGoose** [Skoolgq/Polaris#27]
![Screenshot 2024-02-04 6 03 41 PM](https://github.com/Skoolgq/Polaris/assets/65687266/fde8c9cd-c271-411f-998d-2cf203c9c0f9)
I continuously get the same error and has not been fixed yet, it usually happens once or twice and fixes itself, but it doesn't for some reason.

**Comment by Russell2259** [comment]
It looks like ultraviolet can't access indexedDB, which is a storage system for the web. If you could tell us the url this error is occurring on, and browser you're using we will be able to further diagnose this issue.

**Comment by UnderC0verGoose** [comment]
> It looks like ultraviolet can't access indexedDB, which is a storage system for the web. If you could tell us the url this error is occurring on, and browser you're using we will be able to further diagnose this issue.

This is happening on https://space-4dpi.onrender.com/, and I am using google chrome.
