### ISSUE TITLE
Games giving me Half the screen

### ISSUE THREAD

**Issue by UnderC0verGoose** [Skoolgq/Polaris#29]
When I try playing cod mobile or roblox it continuously gives me a half screen and I'm not sure if this is on uv's side or now.gg's.
![Screenshot 2024-02-17 7 41 02 AM](https://github.com/Skoolgq/Polaris/assets/65687266/79cb6347-da38-423d-96aa-a1385b37edc1)

**Comment by fowntain** [comment]
> When I try playing cod mobile or roblox it continuously gives me a half screen and I'm not sure if this is on uv's side or now.gg's. ![Screenshot 2024-02-17 7 41 02 AM](https://private-user-images.githubusercontent.com/65687266/305644126-79cb6347-da38-423d-96aa-a1385b37edc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDY1MTIsIm5iZiI6MTcwODU0NjIxMiwicGF0aCI6Ii82NTY4NzI2Ni8zMDU2NDQxMjYtNzljYjYzNDctZGEzOC00MjNkLTk2YWEtYTEzODViMzdlZGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIwMTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYTA1ODFmYzhhYzhmODE0ZDVjN2YzYjA5ZjBjMzE0YWI5NWI5MzQwZjZiMmQyOTJiZGU1ZDVhNjVmZThlMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2JuzThCPQwUTayv2y4W7cShBCscd-37Mq17g2VJTIhA)

this was under nowgg's side. we've switched our source and this should be fixed now.
