### ISSUE TITLE
Won't Deploy on Render anymore

### ISSUE THREAD

**Issue by UnderC0verGoose** [Skoolgq/Polaris#31]
![image](https://github.com/Skoolgq/Polaris/assets/65687266/5167799f-bdf6-43f6-9978-fbfc73bc3309)
Render doesn't seem to deploy polaris anymore and just gives me an error message.

**Comment by Russell2259** [comment]
Render might not allow proxies on their platform.

**Comment by fowntain** [comment]
@UnderC0verGoose Try forking the repo then go to render and pick the deploy from github button. Then, choose your fork. It should fix it

**Comment by plastics-eater** [comment]
solution found
