### ISSUE TITLE
Still Won't allow me to Deploy

### ISSUE THREAD

**Issue by UnderC0verGoose** [Skoolgq/Polaris#32]
Render still won't allow me to deploy. What should I do? 
![image](https://github.com/Skoolgq/Polaris/assets/65687266/6adaf9fb-16ae-4761-a636-dfcee8e95ca9)

**Comment by YourBloxJade** [comment]
idk maybe try and use docker + blueprint, also this could've that the repository is blocked, so fork it.
though I use dockerhub and transfer my github to it and host on render

**Comment by Russell2259** [comment]
It looks like you're creating a blueprint. Try removing the render.yaml from your fork and deploying again.

**Comment by UnderC0verGoose** [comment]
Like removing the render.yaml file? If so I've already tried that and it still doesn't work.

**Comment by ms72b** [comment]
just use codespace make it public and deploy it there 💀
