### ISSUE TITLE
Not professional looking

### ISSUE THREAD

**Issue by Nebelung-Dev** [Skoolgq/Polaris#34]
For being marketed as *the* professional unblocked games site it does not professional.

**Comment by fowntain** [comment]
Ha. How's that?

**Comment by Nebelung-Dev** [comment]
![image](https://github.com/Skoolgq/Polaris/assets/81875430/c53cde2e-317b-4f9d-bc7d-3d4b079fa0ee)
Its things like this where things overlap and is not consistent.
![image](https://github.com/Skoolgq/Polaris/assets/81875430/bdec9735-9d64-4a41-9e31-9566e7bf8c1f)
or like this where the positioning is all off and the contrast is terrible.

Anyway the issue was kind of a joke anyways it looks fine for a ubg site

Also I am still working on my site, a complete remake from scratch with the last commit only a week ago.
Lets see if I am qualified, take a look,
![image](https://github.com/Skoolgq/Polaris/assets/81875430/7bef6f48-d117-47b9-b47f-b83300332232)
![image](https://github.com/Skoolgq/Polaris/assets/81875430/ca9479a9-333c-4254-9bfb-ecca596c5824)
I'm not sure your qualified to speak at the moment considering you use `<br>` way to much and cant figure out padding
