### ISSUE TITLE
None of the button appear deploying on vercel

### ISSUE THREAD

**Issue by Bryandrr** [Skoolgq/Polaris#35]
![Screenshot 2024-04-03 8 35 54 PM](https://github.com/Skoolgq/Polaris/assets/163682155/48df808d-2269-4b01-8baf-75aa85073b9f)

**Comment by Erik-Da-coder** [comment]
Same

**Comment by aigamesmast** [comment]
same

**Comment by ytrewq000** [comment]
Same

**Comment by JustJxrdanWasDefinetlyTaken** [comment]
> hideipnetwork

aye fuck you for tryna self advertize your shitty service
