### ISSUE TITLE
All I Get Is A White Screen

### ISSUE THREAD

**Issue by AltAccount10** [Skoolgq/Polaris#42]
Whenever I try to use the proxy or games, or apps or really anything. I will click on it and then it ends up just showing me a white screen. It still says that I need to reload page if it says that the bare server didn't work. So it just pops up and then I get a white screen. Please help.

**Comment by AltAccount10** [comment]
![Uploading Screenshot 2024-10-17 10.45.44 AM.png…]()

**Comment by AltAccount10** [comment]
![Screenshot 2024-10-17 10 45 44 AM](https://github.com/user-attachments/assets/f429b8cf-eb87-41af-b051-eea3693eba5b)

**Comment by hswiehe000** [comment]
me too! did you use codesandbox? i did
